"""empty message

Revision ID: 94bdf8fbd7d6
Revises: 5eb7258f895b
Create Date: 2023-01-30 11:52:45.079906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94bdf8fbd7d6'
down_revision = '5eb7258f895b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'description')
    # ### end Alembic commands ###
